config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  get 'about', to: 'pages#about'

  get 'services', to: 'pages#services'

  get 'products', to: 'pages#products'

  get 'cart', to: 'pages#shopping_cart'

  get 'contact', to: 'pages#contact_us'

  resources :blogs
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
end

app/models/guest_user.rb
class GuestUser < User
  attr_accessor :name, :first_name, :last_name, :email, :id
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :name

  def first_name
    self.name.split.first
  end

  def last_name
    self.name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include DeviseWhitelist
  include SetSource
  include CurrentUserConcern
  include SetTitle
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
   access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit]}, site_admin: :all

  def index
    @blogs = Blog.all
  end

  def show
    @page_title = @blog.title
  end

  def new
    @blog = Blog.new
  end

  def edit
  end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Your post was created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Your post was updated.' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Your post was deleted.' }
    end
  end

  private

    def set_blog
      @blog = Blog.find(params[:id])
    end

    def blog_params
      params.require(:blog).permit(:title, :subtitle, :body, :author)
    end
end

app/controllers/concerns/current_user_concern.rb
module CurrentUserConcern
  extend ActiveSupport::Concern

  def current_user
    super || guest_user
  end

  def guest_user
    guest = GuestUser.new
    guest.name = "Guest User"
    guest.first_name = "Guest"
    guest.last_name = "User"
    guest.email = "guest@example.com"
    guest
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern

  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/concerns/set_source.rb
module SetSource
  extend ActiveSupport::Concern

  included do
    before_action :set_source
  end

  def set_source
    session[:source] = params[:q] if params[:q]
  end
end

app/controllers/concerns/set_title.rb
module SetTitle
  extend ActiveSupport::Concern

  included do
    before_action :set_title
  end

  def set_title
    @page_title = "MonthOneHwApp | Authentication and Authorizaton"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def services
  end

  def products
  end

  def shopping_cart
  end

  def contact_us
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def login_helper style = ''
    if current_user.is_a?(GuestUser)
      (link_to "Register", new_user_registration_path, class: style) + 
      " ".html_safe +
      (link_to "Login", new_user_session_path, class: style)
    else
      link_to "Logout", destroy_user_session_path, method: :delete, class: style
    end
  end

  def copyright_generator
    DangeloViewTool::Renderer.copyright "Tania D'Angelo", 'All rights reserved.' 
  end

  def nav_items
    [
      {
        url: root_path,
        title:'Home'
      },
      {
        url: about_path,
        title:'About'
      },
      {
        url: services_path,
        title:'Our Services'
      },
      {
        url: products_path,
        title:'Our Products'
      },
      {
        url: cart_path,
        title:'Shopping Cart'
      },
      {
        url: blogs_path,
        title:'Blog'
      },
      {
        url: contact_path,
        title:'Contact'
      }
    ]
  end

  def nav_helper style, tag_type
    nav_links = ''

    nav_items.each do |item|
    nav_links << "<#{tag_type}><a href='#{item[:url]}' class='#{style} #{active? item[:url]}'>#{item[:title]}</a></#{tag_type}>" 
  end

    nav_links.html_safe
  end

  def active? path
    "active" if current_page? path
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_blog.html.erb
<div class="blog-post">
  <h2 class="blog-post-title"><%= link_to blog.title.upcase, blog %></h2>
  <p class="blog-post-meta">Published <%=distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <p>
    <%= blog.author %>
  </p>

  <% if logged_in?(:site_admin) %>
    <p class="blog-post-meta">
    <%= link_to 'Create a Post', new_blog_path(blog) %> |
    <%= link_to 'Edit', edit_blog_path(blog) %> |
    <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
    <p>
  <% end %>
</div>

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-group">
    <%= form.text_field :title, id: :blog_title, class: 'form-control', placeholder: 'Title' %>
  </div>

  <div class="form-group">
    <%= form.text_area :body, id: :blog_body, class: 'form-control', rows: 15, placeholder: 'Content' %>
  </div>

   <div class="form-group">
    <%= form.text_field :author, id: :blog_author, class: 'form-control', placeholder: 'Author' %>
  </div>

  <div class="form-group">
    <%= form.submit "Submit", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<div class="col-sm-12 blog-main">
  
  <h2>Editing Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Show', @blog %> |
  <%= link_to 'Back', blogs_path %>

</div>

app/views/blogs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-">
      <h4>Latest Posts</h4>

      <hr>
        
        <div class="group1 col-sm-12 justify-content-end">
          <% @blogs.each do |blog| %>
            <div class="row">
              <div class=" col-md-4">
                <%= link_to blog.title, blog %>
              </div>

              <div class="col-md-4">
                <p class="blog-post-meta">Published <%=distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>
              </div>

              <div class="col-md-4">
                <%= blog.author %>
              </div>
            </div>

            <div class="row">
              <%= blog.body %>
            </div>

            <% if logged_in?(:site_admin) %>
              <p class="blog-post-meta">
              <%= link_to 'Create a Post', new_blog_path(blog) %> |
              <%= link_to 'Edit', edit_blog_path(blog) %> |
              <%= link_to 'Delete Post', blog, method: :delete, data: { confirm: 'Are you sure?' } %>
              <p>
            <% end %>
          <% end %>
        </div>  
    </div>
  </div>
</div>

app/views/blogs/new.html.erb
<div class="col-sm-12 blog-main">
  
  <h2>New Blog</h2>

  <%= render 'form', blog: @blog %>

  <%= link_to 'Back', blogs_path %>
</div>

app/views/blogs/show.html.erb
<div class="col-sm-12 blog-main">
  
  <h2><%= @blog.title %></h2>
  
  <%= link_to 'Edit', edit_blog_path(@blog) if logged_in?(:site_admin) %>
    
  <p>
    <%= @blog.body %>
  </p>

  <h5>
    <%= @blog.author %>
  </h5>

<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="site-wrapper">  
      <div class="site-wrapper-inner">
        <div class="cover-container">

          <div id="background"></div>

          <%= render "shared/application_nav" %>

          <%= yield %>

          <div class="row justify-content-center">
            <%= render "shared/application_footer" %>
          </div>

        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'blogs', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= login_helper %>

    <%= yield %>

    <%= render "shared/nav", location: 'bottom' %>

    <% if session[:source] %>
      <p>Thanks for visiting me from <%= session[:source] %></p>
    <% end %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="col-md-12">
     <p>About Us</p>
  </div>
</div>

app/views/pages/contact_us.html.erb
<h3>Give us a call!</h3>

<hr>

<div class= "row">
  <div class="col-md-6">
    <h2>Location</h2>
    
    <p>Lafayette Parish, LA 70592</p>

    <h2>Phone</h2> 
    
    <p><%= number_to_phone "555-555-5555" %></p>

    <h2>Email</h2> 

    <p><%= link_to "Email me", "mailto:test@outlook.com?subject=website search-bayou builds" %></p>
  </div>

  <div class="col-md-6">
  <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d110332.15533441983!2d-92.10860974415574!3d30.211976383878223!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x86249c4364c5d89b%3A0xc94a752492f7ff13!2sLafayette%2C+LA!5e0!3m2!1sen!2sus!4v1509338729315" width="350" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
  </div>
</div>

app/views/pages/home.html.erb
<div class="inner cover">
  <h1 class="cover-heading">MonthOneHwApp</h1>
  <p class="lead">“Have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary." - Steve Jobs</p>
  <p class="lead">
    <%= link_to "About", about_path, class: "btn btn-lg btn-secondary" %>
  </p>
</div>

app/views/pages/products.html.erb
<div class="continer">
  <div class="row">
    <div class="group1 col-sm-12">
      <li class="media">
        <%= image_tag "workshop.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "tools.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "workshop.jpg", width: 200, alt: "Product Image" %>
      </li>
    </div>
  </div>
  <div class="row">
    <div class="group1 col-sm-12">
      <li class="media my-4">
        <%= image_tag "tools.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
        <%= image_tag "manypens.jpg", width: 120, alt: "Product Image" %>
      </li>
    </div>
  </div>
</div>

<div class="row">
  <div class="group1 col-sm-12">
    <li class="media">
      <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
      <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
      <%= image_tag "manypens.jpg", width: 120, alt: "Product Image" %>
      <%= image_tag "tools.jpg", width: 200, alt: "Product Image" %>
    </li>
  </div>
</div>

app/views/pages/services.html.erb
<ul class="list-unstyled">
  <li class="media">
    <%= image_tag "workshop.jpg", width: 200, alt: "Product Image" %>
    <div class="media-body">
      <h5 class="mt-0 mb-1">List-based media object</h5>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
  </li>
  <li class="media my-4">
    <%= image_tag "tools.jpg", width: 200, alt: "Product Image" %>
    <div class="media-body">
      <h5 class="mt-0 mb-1">List-based media object</h5>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
  </li>
  <li class="media">
    <%= image_tag "customworkfiretruckflag.jpg", width: 200, alt: "Product Image" %>
    <div class="media-body">
      <h5 class="mt-0 mb-1">List-based media object</h5>
      Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
    </div>
  </li>
</ul>

app/views/pages/shopping_cart.html.erb
<h1>Shopping Cart</h1>

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_nav.html.erb
<div>
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About", about_path %></div>
  <div><%= link_to "Our Services", services_path %></div>
  <div><%= link_to "Our Products", products_path %></div>
  <div><%= link_to "Shopping Cart", cart_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Contact Us", contact_path %></div>
</div>